- name: Merge pull requests
  uses: pascalgn/automerge-action@v0.13.0

env: 
GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
MERGE_LABELS: "" 
MERGE_REMOVE_LABELS: "" 
MERGE_METHOD: "merge" 
MERGE_COMMIT_MESSAGE: "pull-request-description" 
MERGE_FORKS: "true" 
MERGE_RETRIES: "2" 
MERGE_RETRY_SLEEP: "10000" 
UPDATE_LABELS: "" 
UPDATE_METHOD: "merge"
